---
# vars file for openssh
_openssh_packages:
  default:
    - openssh-server
  Archlinux:
    - openssh
  openSUSE Leap:
    - openssh

openssh_packages: "{{ _openssh_packages[ansible_distribution] | default(_openssh_packages['default']) }}"

_openssh_key_types:
  default:
    - rsa
    - ecdsa
    - ed25519
  CentOS-6:
    - rsa
    - ecdsa

openssh_key_types: "{{ _openssh_key_types[ansible_distribution ~ '-' ~ ansible_distribution_major_version] | default(_openssh_key_types['default']) }}"

_openssh_run_directory:
  default: /var/run/sshd/
  Debian: /run/sshd
  Ubuntu: /run/sshd

openssh_run_directory: "{{ _openssh_run_directory[ansible_distribution] | default(_openssh_run_directory['default']) }}"

openssh_configuration_file: /etc/ssh/sshd_config

openssh_service: sshd

_openssh_template_src:
  Alpine: sshd_config_Alpine.j2
  Archlinux: sshd_config_Archlinux.j2
  CentOS-6: sshd_config_CentOS-6.j2
  CentOS-7: sshd_config_CentOS-7.j2
  Debian: sshd_config_Debian.j2
  Fedora: sshd_config_Fedora.j2
  openSUSE Leap: sshd_config_openSUSE.j2
  Ubuntu: sshd_config_Debian.j2

openssh_template_src: "{{ _openssh_template_src[ansible_distribution ~ '-' ~ ansible_distribution_major_version] | default(_openssh_template_src[ansible_distribution]) }}"

_openssh_template_mode:
  Alpine: "0644"
  Archlinux: "0644"
  CentOS: "0600"
  Debian: "0644"
  Fedora: "0600"
  openSUSE Leap: "0640"
  Ubuntu: "0644"

openssh_template_mode: "{{ _openssh_template_mode[ansible_distribution] }}"
