---
# tasks file for docker-image-run
- name: pull an image
  docker_image:
    name: node
    force: yes

- name: Run docker image
  docker_service:
        recreate: always
        project_name: some-node
        definition:
          version: '2'
          services:
            node:
              image: node
              volumes:
                - "{{nodejs_path}}:/usr/src/app"
              working_dir: "/usr/src/app"
              ports:
                - "3000:3000"
              command: "node server.js"
#      register: output

#  - debug:
#        var: output
