
---
- hosts: all
  become: yes
#    become_user:root
  remote_user: yog
  roles:
     - role: ansible-role-jenkins
       tags: jenkins
     - role: ansible-role-docker
       tags: docker
     - role: docker-nodejs-run
       tags: nodejs
     - role: docker-nginx-run
       tags: nginx
  vars:
      docker_package: docker.io

